// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlcH6pV2YT1CT-i-4X-8ek9kHBYEW8hq4',
    appId: '1:546795500354:android:1e985be52e85bb062fcedb',
    messagingSenderId: '546795500354',
    projectId: 'fahmi-ditonton-apps',
    storageBucket: 'fahmi-ditonton-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ8L40a8APs1wMs233Wb0oTRGVV8Rryz4',
    appId: '1:546795500354:ios:0a87ba31cae2918e2fcedb',
    messagingSenderId: '546795500354',
    projectId: 'fahmi-ditonton-apps',
    storageBucket: 'fahmi-ditonton-apps.appspot.com',
    iosClientId:
        '546795500354-melhgrsujcjoro3ehcr74lj7f2i97at1.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
